# Generated by Django 4.2.7 on 2023-11-04 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fns', '0002_shorttermcourse'),
    ]

    operations = [
        migrations.AddField(
            model_name='shorttermcourse',
            name='image',
            field=models.ImageField(default=None, upload_to=''),
        ),
    ]
