# Generated by Django 4.2.7 on 2023-11-04 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fns', '0003_shorttermcourse_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='shorttermcourse',
            name='additionalinfo_set',
            field=models.JSONField(default=[]),
        ),
        migrations.AlterField(
            model_name='shorttermcourse',
            name='amount',
            field=models.FloatField(),
        ),
    ]
