# Generated by Django 4.2.7 on 2023-11-05 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fns', '0004_shorttermcourse_additionalinfo_set_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shorttermcourse',
            name='additionalinfo_set',
        ),
    ]
